export enum PHOENIX_MAPPING {
  ITEM = 'ITEM',
  VALUE = 'VALUE',
  SERIES = 'SERIES',
  CATEGORY = 'CATEGORY',
  CURRENT = 'CURRENT',
  PREVIOUS = 'PREVIOUS',
  TARGET = 'TARGET',
  MIN = 'MIN',
  MAX = 'MAX'
}
