export enum MAPPING {
  ITEM = 'ITEM',
  VALUE = 'VALUE',
  SERIES = 'SERIES',
  CATEGORY = 'CATEGORY',
  CURRENT = 'CURRENT',
  PREVIOUS = 'PREVIOUS',
  TARGET = 'TARGET',
  MIN = 'MIN',
  MAX = 'MAX',
  BUBBLESIZE = 'BUBBLESIZE',
  XTIME = 'XTIME',
  COUNTRY = 'COUNTRY',
  LATITUDE = 'LATITUDE',
  LONGITUDE = 'LONGITUDE'
}
